version: "3.8"
services:
  dev-postgres:
    image: postgres:15.1-alpine
    # command: postgres -c log_destination=stderr -c log_statement=all -c 
    command: ["postgres", "-c", "log_destination=stderr", "-c", "log_statement=all", "-c", "log_min_duration_statement=0"]
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: udemy
      POSTGRES_PASSWORD: udemy
      POSTGRES_DB: udemy
    restart: always
    networks:
      - lesson
    logging:
      options:
        max-size: "10k"
networks:
  lesson:
